### ISSUE TITLE
Core-logic TODO

### ISSUE THREAD

**Issue by Ericufo** [salad14/2024-TongjiUniversity-Programming-Paradigm#2]
1. board class
2. player class
3. Card classes (Minions, Spells, Weapons)
4. hero classes? (need to be discussed)
5. combining all these things together.

**Comment by singlying** [comment]
还差一些，可以参考 \Classes\board\board.h 下面的

**Comment by singlying** [comment]
现在各个模块只是完成了一个基本的框架，card class只完成了minioncard，你可以考虑开始做spell card 和 weaponcard. 
另外，weapon的结构也没有实现，可以考虑开始先形成一个框架

**Comment by Ericufo** [comment]
copy that.
